export enum PokemonType {
  Normal = "normal",
  Fire = "fire",
  Water = "water",
  Electric = "electric",
  Grass = "grass",
  Ice = "ice",
  Fighting = "fighting",
  Poison = "poison",
  Ground = "ground",
  Flying = "flying",
  Psychic = "psychic",
  Bug = "bug",
  Rock = "rock",
  Ghost = "ghost",
  Dragon = "dragon",
  Dark = "dark",
  Steel = "steel",
  Fairy = "fairy",
}

export const colorMapping: Record<PokemonType, string> = {
  normal: "#A8A878",
  fire: "#F08030",
  water: "#6890F0",
  electric: "#F8D030",
  grass: "#78C850",
  ice: "#98D8D8",
  fighting: "#C03028",
  poison: "#A040A0",
  ground: "#E0C068",
  flying: "#A890F0",
  psychic: "#F85888",
  bug: "#A8B820",
  rock: "#B8A038",
  ghost: "#705898",
  dragon: "#7038F8",
  dark: "#705848",
  steel: "#B8B8D0",
  fairy: "#EE99AC",
};

export const colorHoverMapping: Record<PokemonType, string> = {
  normal: " hover: #C6C6A7",
  fire: " hover: #F5AC78",
  water: " hover: #9DB7F5",
  electric: " hover: #FAE078",
  grass: " hover:  #A7DB8D",
  ice: " hover: #BCE6E6",
  fighting: " hover: #D67873",
  poison: "  hover: #C183C1",
  ground: " hover: #EBD69D",
  flying: " hover: #C6B7F5",
  psychic: " hover: #FA92B2",
  bug: " hover: #C6D16E",
  rock: " hover: #D1C17D",
  ghost: " hover: #A292BC",
  dragon: " hover: #A27DFA",
  dark: " hover:  #A29288",
  steel: " hover: #D1D1E0",
  fairy: " hover: #F4BDC9",
};
