export enum PokemonType {
  Normal = "normal",
  Fire = "fire",
  Water = "water",
  Electric = "electric",
  Grass = "grass",
  Ice = "ice",
  Fighting = "fighting",
  Poison = "poison",
  Ground = "ground",
  Flying = "flying",
  Psychic = "psychic",
  Bug = "bug",
  Rock = "rock",
  Ghost = "ghost",
  Dragon = "dragon",
  Dark = "dark",
  Steel = "steel",
  Fairy = "fairy",
}

export const colorMapping: Record<PokemonType, string> = {
  [PokemonType.Normal]: "#A8A878 hover: #C6C6A7",
  [PokemonType.Fire]: "#F08030 hover: #F5AC78",
  [PokemonType.Water]: "#6890F0 hover: #9DB7F5",
  [PokemonType.Electric]: "#F8D030 hover: #FAE078",
  [PokemonType.Grass]: "#78C850 hover:  #A7DB8D",
  [PokemonType.Ice]: "#98D8D8 hover: #BCE6E6",
  [PokemonType.Fighting]: "#C03028 hover: #D67873",
  [PokemonType.Poison]: "#A040A0  hover: #C183C1",
  [PokemonType.Ground]: "#E0C068 hover: #EBD69D",
  [PokemonType.Flying]: "#A890F0 hover: #C6B7F5",
  [PokemonType.Psychic]: "#F85888 hover: #FA92B2",
  [PokemonType.Bug]: "#A8B820 hover: #C6D16E",
  [PokemonType.Rock]: "#B8A038 hover: #D1C17D",
  [PokemonType.Ghost]: "#705898 hover: #A292BC",
  [PokemonType.Dragon]: "#7038F8 hover: #A27DFA",
  [PokemonType.Dark]: "#705848 hover:  #A29288",
  [PokemonType.Steel]: "#B8B8D0 hover: #D1D1E0",
  [PokemonType.Fairy]: "#EE99AC hover: #F4BDC9",
};
